# Generated by Django 2.0.6 on 2019-02-28 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ValidationApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserModel',
        ),
    ]
