# Generated by Django 2.0.6 on 2019-02-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ValidationApp', '0002_auto_20190228_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='CocktailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('alcoholContent', models.DecimalField(decimal_places=3, default=0.0, max_digits=6)),
                ('servingContainer', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
